{% set name = "htdp" %}
{% set version = "1.0_isis7" %}
{% set sha256 = "7b15900a896460c523cd844e57f8e5ebc277222835b4b6535e28283f5b953d5b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: HTDP-download.zip
  url: http://www.ngs.noaa.gov/TOOLS/Htdp/HTDP-download.zip
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('gfortran') }}
  host:

  run:

test:
  commands:

about:
  home: https://geodesy.noaa.gov/TOOLS/Htdp/HTDP-user-guide.pdf
  license: APACHE
  summary: 'Horizontal Time-Dependent Positioning'
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - oleg-alexandrov

